export const SET_INPUT_MODAL_VISIBLE = 'SET_INPUT_MODAL_VISIBLE';
export const SET_DETAIL_MODAL_VISIBLE = 'SET_DETAIL_MODAL_VISIBLE';
export const SET_SORT_MODAL_VISIBLE = 'SET_SORT_MODAL_VISIBLE';
export const SET_PROGRESS_MODAL_VISIBLE = 'SET_PROGRESS_MODAL_VISIBLE';

export const ADD_ROUTINE = 'ADD_ROUTINE';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const COMPLETE_PROGRESS = 'COMPLETE_PROGRESS';

export const SUCCESS_ADD_ROUTINE = 'SUCCESS_ADD_ROUTINE';
export const SUCCESS_DELETE_ROUTINE = 'SUCCESS_DELETE_ROUTINE';
export const SUCCESS_UPDATE_PROGRESS = 'SUCCESS_UPDATE_PROGRESS';
export const SUCCESS_GET_ROUTINE = 'SUCCESS_GET_ROUTINE';

export const CHANGE_ROUTINE_TITLE = 'CHANGE_ROUTINE_TITLE';
export const CHANGE_DEFAULT_COUNT = 'CHANGE_DEFAULT_COUNT';
export const SUBMIT_ADD_ROUTINE = 'SUBMIT_ADD_ROUTINE';

export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_CREATED = 'SORT_BY_CREATED';
export const SORT_BY_COMPLETED = 'SORT_BY_COMPLETED';

export const CHANGE_LOGIN_EMAIL = 'CHANGE_LOGIN_EMAIL';
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD';

export const LOGIN = 'LOGIN';
export const SIGNOUT = 'SIGNOUT';
export const SIGNUP = 'SIGNUP';

export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESS_SIGNOUT = 'SUCCESS_SIGNOUT';
export const SUCCESS_SIGNUP = 'SUCCESS_SIGNUP';

export const ADD_TASK = 'ADD_TASK';
