export const SET_INPUT_MODAL_VISIBLE = 'SET_INPUT_MODAL_VISIBLE';
export const SET_DETAIL_MODAL_VISIBLE = 'SET_DETAIL_MODAL_VISIBLE';
export const ADD_ROUTINE = 'ADD_ROUTINE';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const GET_ROUTINE_FROM_CACHE = 'GET_ROUTINE_FROM_CACHE';
export const SUCCESS_ADD_ROUTINE = 'SUCCESS_ADD_ROUTINE';
export const SUCCESS_DELETE_ROUTINE = 'SUCCESS_DELETE_ROUTINE';
export const SUCCESS_UPDATE_PROGRESS = 'SUCCESS_UPDATE_PROGRESS';
export const SUCCESS_GET_ROUTINE = 'SUCCESS_GET_ROUTINE';

export const CHANGE_ROUTINE_TITLE = 'CHANGE_ROUTINE_TITLE';
export const CHANGE_DEFAULT_COUNT = 'CHANGE_DEFAULT_COUNT';
export const SUBMIT_ADD_ROUTINE = 'SUBMIT_ADD_ROUTINE';

export const CHANGE_LOGIN_EMAIL = 'CHANGE_LOGIN_EMAIL';
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD';
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SIGNOUT = 'SIGNOUT';
export const SUCCESS_SIGNOUT = 'SUCCESS_SIGNOUT';
export const IS_LOGGEDIN = 'IS_LOGGEDIN';
export const SUCCESS_IS_LOGGEDIN = 'SUCCESS_IS_LOGGEDIN';
export const FAILURE_IS_LOGGEDIN = 'FAILURE_IS_LOGGEDIN';