export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const SET_INPUT_MODAL_VISIBLE = 'SET_INPUT_MODAL_VISIBLE';
export const SET_DETAIL_MODAL_VISIBLE = 'SET_DETAIL_MODAL_VISIBLE';
export const ADD_ROUTINE = 'ADD_ROUTINE';
export const SET_ROUTINE_STORAGE = 'SET_ROUTINE_STORAGE';
export const SUCCESS_ADD_ROUTINE = 'SUCCESS_ADD_ROUTINE';